services:
  - type: web
    name: calc2-bot
    env: python
    plan: free
    buildCommand: pip install -r services/cas-python/requirements.txt
    startCommand: gunicorn -k uvicorn.workers.UvicornWorker services.cas-python.app.main:app --bind 0.0.0.0:$PORT
    autoDeploy: true