services:
  - type: web
    name: calc2-bot
    env: python
    plan: free
    buildCommand: pip install -r services/cas-python/requirements.txt
    startCommand: uvicorn services.cas-python.app.main:app --host 0.0.0.0 --port 10000
    autoDeploy: true