services:
  - type: web
    name: calc2-bot
    env: python
    plan: free
    buildCommand: "pip install -r services/cas-python/requirements.txt"
    startCommand: "uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    workingDirectory: services/cas-python
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
    autoDeploy: true